name: Release Gem

on:
  push:tags
    branches:
      - v1.*
      - v2.*

jobs:
  release-gem:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ðŸš€ Release gem
        uses: dawidd6/action-publish-gem@v1
        with:
          github_token: ${{secrets.GH_CREDENTIALS}}
          api_key: ${{secrets.RUBYGEMS_API_KEY}}
